### ISSUE TITLE
[Briefings][Monad for users] 认领

### ISSUE THREAD

**Issue by smallfu6** [monad-cn/docs#1]
翻译官网的 [Monad for users](https://docs.monad.xyz/briefings/monad-for-users)节

**Comment by Anyi-zheng** [comment]
认领

**Comment by smallfu6** [comment]
@Anyi-zheng ok

**Comment by smallfu6** [comment]
@Anyi-zheng 已经有[Monad中文版](https://monad.docszh.com/)了， 停止翻译
