### ISSUE TITLE
[Technical discussion][Consensus][MonadBFT] 认领

### ISSUE THREAD

**Issue by jeasonzhang-eth** [monad-cn/docs#7]
翻译官网的[MonadBFT](https://docs.monad.xyz/technical-discussion/consensus/monadbft)章节

**Comment by wfnuser** [comment]
I'd like to have a try on this.

**Comment by smallfu6** [comment]
@wfnuser ok

**Comment by smallfu6** [comment]
@wfnuser  已经有[Monad中文版](https://monad.docszh.com/)了， 停止翻译
